---
title: "Covid19"
author: "Matt DeSaix"
date: "3/28/2020"
output: html_document
---

Below I will pull the data from the NYT repository on github.  The two data sets are state-level and county-level coronavirus cases and deaths.

```{r, echo = F, message = F}
library(tidyverse)
library(urbnmapr)

# Get COVID data from NYT's github page
county.url <- "https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv"
covid.counties <- read_csv(url(county.url))

state.url <- "https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv"
covid.states <- read_csv(url(state.url))
```

## Looking at some stats



### United States cases and deaths

```{r}
daily.sum <- covid.states %>%
  group_by(date) %>%
  summarise(fullcases = sum(cases),
            fulldeaths = sum(deaths))

daily.sum %>%
  ggplot() +
  geom_point(aes(x = date, y = log10(fullcases), color = "Cases")) +
  geom_point(aes(x = date, y = log10(fulldeaths), color = "Deaths")) +
  xlab("Date") +
  ylab("Cases and Deaths (Log10)") +
  theme_bw() +
  theme(legend.title = element_blank(),
        legend.position = c(0.1, 0.85),
        legend.box.background = element_rect(color = "black"))
```


```{r, echo = F}
daily.sum %>%
  ggplot() +
  geom_point(aes(x = date, y = fullcases, color = "Cases")) +
  geom_point(aes(x = date, y = fulldeaths, color = "Deaths")) +
  xlab("Date") +
  ylab("Cases and Deaths") +
  theme_bw() +
  theme(legend.title = element_blank(),
        legend.position = c(0.1, 0.85),
        legend.box.background = element_rect(color = "black"))
```





```{r}
covid.counties.co <- covid.counties %>%
  filter(state == "Colorado")
ggplot(covid.counties.co, aes(x = date, y = cases)) +
  geom_point(aes(color = county)) +
  theme_bw()
```



```{r, echo = F}
co.counties.death <- covid.counties.co %>%
  filter(deaths > 0)
ggplot(co.counties.death, aes(x = date, y = deaths)) +
  geom_point(position = position_jitter(w=0.1, h = 0.1),
             aes(color = county, size  = 4), alpha = 0.75) +
  theme_bw()
```


## Maps


```{r, echo = F}
countydata <- urbnmapr::countydata
counties <- urbnmapr::counties %>%
  mutate(fips = county_fips)

full.covid.tib <- covid.counties %>%
  filter(date == max(covid.counties$date)) %>%
  right_join(counties, by = "fips") %>%
  mutate(log_cases = log10(cases)) %>%
  mutate(log_casesFull = replace_na(log_cases, 0))
  

full.covid.tib %>%
  ggplot(aes(long, lat, group = group, fill = log_casesFull)) +
  geom_polygon(color = NA) +
  coord_map(projection = "albers", lat0 = 39, lat1 = 45) +
  labs(fill = "Number of Coronavirus Cases (Log10)") +
  theme_bw()
  
```

### Map above by states

```{r, echo =F}


full.covid.tib %>%
  filter(state_name == "Colorado")
  ggplot(aes(long, lat, group = group, fill = log_casesFull)) +
  geom_polygon(color = NA) +
  coord_map(projection = "albers", lat0 = 39, lat1 = 45) +
  labs(fill = "Number of Coronavirus Cases (Log10)") +
  theme_bw()
```



### Covid by states

```{r, echo = F}
states <- urbnmapr::states %>%
  mutate(fips = state_fips)

full.covid.states <- covid.states %>%
  filter(date == max(covid.states$date)) %>%
  right_join(states, by = "fips") %>%
  mutate(log_cases = log10(cases))


full.covid.states %>%
  ggplot(aes(long, lat, group = group, fill = log_cases)) +
  geom_polygon(color = NA) +
  coord_map(projection = "albers", lat0 = 39, lat1 = 45) +
  theme(legend.title = element_text()) +
  labs(fill = "Number of Coronavirus Cases (Log10)") +
  theme_bw()
```



### Covid county points scaled

i.e. remaking the NYT maps here

``` {r, echo = F}

county_location_cases <- full.covid.tib %>%
  group_by(fips) %>%
  summarise(mean_cases = mean(cases),
            mean_logcases = mean(log_casesFull),
            county_lat = mean(lat), 
            county_long = mean(long),
            state = unique(state)) %>%
  filter(mean_cases != "NA")

size_breaks <- c(1,10,50, 100, 500, 1000)

full.covid.states %>%
  ggplot() +
  geom_polygon(aes(long, lat, group = group), 
               fill="gray95", 
               color = "gray70",
               size = 0.1) +
  coord_map(projection = "albers", lat0 = 39, lat1 = 45) +
  geom_point(data = county_location_cases, 
             aes(x = county_long, y = county_lat, size = mean_cases), 
             color = "red4", 
             fill = adjustcolor("red1", alpha.f = 0.25),
             shape = 21) +
  scale_size(breaks = size_breaks, range = c(.5,25)) +
  theme_bw()
```






```{r, echo = F}
library(gganimate)

full.covid.states2 <- covid.states %>%
  right_join(states, by = "fips") %>%
  mutate(log_cases = log10(cases))

full.covid.tib2 <- covid.counties %>%
  right_join(counties, by = "fips") %>%
  mutate(log_cases = log10(cases)) %>%
  mutate(log_casesFull = replace_na(log_cases, 0))

county_location_cases2 <- full.covid.tib2 %>%
  group_by(fips, date) %>%
  summarise(mean_cases = mean(cases),
            mean_logcases = mean(log_casesFull),
            county_lat = mean(lat), 
            county_long = mean(long)) %>%
  filter(mean_cases != "NA")




p2 <- full.covid.states2 %>%
  ggplot() +
  geom_polygon(aes(long, lat, group = group), 
               fill="gray95", 
               color = "gray70",
               size = 0.1) +
  coord_map(projection = "albers", lat0 = 39, lat1 = 45) +
  geom_point(data = county_location_cases2, 
             aes(x = county_long, 
                 y = county_lat, 
                 size = mean_cases, 
                 group = seq_along(date)), 
             color = "red4", 
             fill = adjustcolor("red1", alpha.f = 0.25),
             shape = 21) +
  transition_states(date) +
  scale_size(breaks = size_breaks, range = c(.5,25)) +
  theme_bw()
p2

```





```{r, echo = F}
p2 <- full.covid.states %>%
  ggplot() +
  geom_polygon(aes(long, lat, group = group), 
               fill="gray95", 
               color = "gray70",
               size = 0.1) +
  coord_map(projection = "albers", lat0 = 39, lat1 = 45) +
  geom_point(data = county_location_cases2, 
             aes(x = county_long, 
                 y = county_lat, 
                 size = mean_cases, 
                 group = seq_along(date)), 
             color = "red4", 
             fill = adjustcolor("red1", alpha.f = 0.25),
             shape = 21) +
  transition_reveal(date) +
  scale_size(breaks = size_breaks, range = c(.5,25)) +
  theme_bw()
p2
```



### States


``` {r, echo = F}

county_location_cases <- full.covid.tib %>%
  group_by(fips) %>%
  summarise(mean_cases = mean(cases),
            mean_logcases = mean(log_casesFull),
            county_lat = mean(lat), 
            county_long = mean(long)) %>%
  filter(mean_cases != "NA")

size_breaks <- c(1,10,50, 100, 500, 1000)

full.covid.states %>%
  ggplot() +
  geom_polygon(aes(long, lat, group = group), 
               fill="gray95", 
               color = "gray70",
               size = 0.1) +
  coord_map(projection = "albers", lat0 = 39, lat1 = 45) +
  geom_point(data = county_location_cases, 
             aes(x = county_long, y = county_lat, size = mean_cases), 
             color = "red4", 
             fill = adjustcolor("red1", alpha.f = 0.25),
             shape = 21) +
  scale_size(breaks = size_breaks, range = c(.5,25)) +
  theme_bw()
```




